export const STEP_ACCOUNT_REGISTRATION = {
  COMPANY_INFORMATION: 'CompanyInformation',
  PAYMENT_INFORMATION: 'PaymentInformation'
};
export const STEP = {
  COMPANY_INFORMATION: 1,
  FEES_AGREEMENT: 2,
  PAYMENT_INFORMATION: 3
};
